
export const courses = [
  {
    slug: 'beginner',
    title: 'Beginner',
    description: 'Start your language journey with fundamental concepts and basic conversational skills.',
    image: '/images/beginner.jpeg',
    aiHint: 'new beginnings',
    language: 'English',
    category: 'professional',
    features: [
      'Learn the alphabet and basic phonics',
      'Introduce yourself and others',
      'Form simple sentences and questions',
      'Build a foundation of essential vocabulary',
    ],
  },
  {
    slug: 'intermediate',
    title: 'Intermediate',
    description: 'Build upon your basic knowledge to engage in more complex conversations.',
    image: '/images/intermediate.jpeg',
    aiHint: 'building blocks',
    language: 'English',
    category: 'professional',
     features: [
      'Expand your vocabulary and idiomatic expressions',
      'Understand and use different verb tenses',
      'Improve listening comprehension skills',
      'Practice conversational fluency',
    ],
  },
  {
    slug: 'advanced',
    title: 'Advanced',
    description: 'Refine your skills to achieve fluency and a native-like command of the language.',
    image: '/images/advanced.jpeg',
    aiHint: 'mountain peak',
    language: 'English',
    category: 'professional',
     features: [
      'Master complex sentence structures',
      'Understand nuanced and idiomatic language',
      'Develop advanced reading and writing skills',
      'Engage in debates and complex discussions',
    ],
  },
  {
    slug: 'early-foundation',
    title: 'Early Foundation',
    description: 'A fun, play-based approach to introduce young learners to the English language.',
    image: '/images/early-foundation.jpeg',
    aiHint: 'children playing',
    language: 'English',
    category: 'kids',
     features: [
      'Learn through songs, games, and stories',
      'Develop basic listening and speaking skills',
      'Build a positive attitude towards learning',
      'Focus on vocabulary for everyday objects',
    ],
  },
  {
    slug: 'phonics-starter',
    title: 'Phonics Starter',
    description: 'Master the sounds of English to build a strong foundation for reading and spelling.',
    image: '/images/phonics-starter.jpeg',
    aiHint: 'alphabet blocks',
    language: 'English',
    category: 'kids',
    features: [
        'Learn letter-sound correspondence',
        'Practice blending and segmenting words',
        'Improve pronunciation and clarity',
        'Build confidence in reading aloud',
    ],
  },
  {
    slug: 'public-speaking',
    title: 'Public Speaking',
    description: 'Develop the confidence and skills to deliver impactful presentations.',
    image: '/images/public-speaking.jpeg',
    aiHint: 'public speaking',
    language: 'English',
    category: 'kids',
    features: [
        'Structure a compelling speech',
        'Use body language effectively',
        'Handle Q&A sessions with ease',
        'Engage and persuade your audience',
    ],
  },
    {
    slug: 'business-communication',
    title: 'Business Communication',
    description: 'Master professional communication for the modern workplace.',
    image: '/images/business-communication.jpeg',
    aiHint: 'business meeting',
    language: 'English',
    category: 'professional',
    features: [
        'Write effective emails and reports',
        'Participate confidently in meetings',
        'Develop professional networking skills',
        'Understand workplace etiquette',
    ],
  },
  {
    slug: 'ielts-accelerator',
    title: 'IELTS Accelerator Program',
    description: 'A focused program to help you achieve your target IELTS score quickly.',
    image: '/images/ielts-accelerator.jpeg',
    aiHint: 'exam success',
    language: 'English',
    category: 'professional',
    features: [
        'Intensive practice for all test sections',
        'Strategies for maximizing your score',
        'Mock tests with detailed feedback',
        'Time management and exam techniques',
    ],
  },
];
