
import { getApp, getApps, initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';
import { getStorage } from 'firebase/storage';

// This config is automatically generated by Firebase Studio.
// Do not change it manually.
const firebaseConfig = {
  "projectId": "verbigo-e-campus",
  "appId": "1:282326473798:web:38035b2ec6b2f3ffe7fe47",
  "storageBucket": "verbigo-e-campus.appspot.com",
  "apiKey": "AIzaSyA3m7mPcP3--NC02nxHuU1elMRuavF7So0",
  "authDomain": "verbigo-e-campus.firebaseapp.com",
  "messagingSenderId": "282326473798"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);
const storage = getStorage(app);

export { app, db, storage };
