import { getApp, getApps, initializeApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

// This config is automatically generated by Firebase Studio.
// Do not change it manually.
const firebaseConfig = {
  "projectId": "verbigo-e-campus",
  "appId": "1:282326473798:web:38035b2ec6b2f3ffe7fe47",
  "storageBucket": "verbigo-e-campus.firebasestorage.app",
  "apiKey": "AIzaSyAZQFPLhs8jlFSOSQ3E-8eQCFjnJmZd4Rg",
  "authDomain": "verbigo-e-campus.firebaseapp.com",
  "messagingSenderId": "282326473798"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const db = getFirestore(app);

export { app, db };
